#!/usr/bin/env python3
"""Embeds the web UI (html/v2) into the firmware.

Concatenates the bundles listed in html/v2/manifest.json exactly like the
PHP bundlers on tehybug.com do, minifies them (terser for the JS when
node_modules has it, a conservative in-house pass for the CSS), gzips them
and writes src/web_ui_bundle.h with PROGMEM arrays the web server streams
at /ui/app.js and /ui/app.css - the copy the device page falls back to when
tehybug.com cannot be reached. The same .gz files land in .build/ui/ for
tools/mock-device.js.

Run by build.sh and by PlatformIO (tools/embed_ui_pio.py) before compiling.
"""
import gzip
import hashlib
import json
import os
import re
import subprocess
import sys

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
V2 = os.path.join(ROOT, 'html', 'v2')
OUT_H = os.path.join(ROOT, 'src', 'web_ui_bundle.h')
OUT_DIR = os.path.join(ROOT, '.build', 'ui')
TERSER = os.path.join(ROOT, 'node_modules', '.bin', 'terser')


def bundle(kind, separator):
    manifest = json.load(open(os.path.join(V2, 'manifest.json')))
    return ''.join(open(os.path.join(V2, kind, f), encoding='utf-8').read() + separator for f in manifest[kind])


def minify_js(js):
    if not os.path.exists(TERSER):
        print('embed-ui: node_modules/.bin/terser not found (npm ci) - embedding the JS unminified', file=sys.stderr)
        return js
    out = subprocess.run([TERSER, '--compress', '--mangle', '--ecma', '2017', '--comments', 'false'],
                         input=js, capture_output=True, text=True, check=True).stdout
    # the minified bundle must still parse
    return out


def minify_css(css):
    # comments, then whitespace runs; spaces around the structural characters
    # (never inside quotes - the data: URI in app.css keeps its spaces)
    css = re.sub(r'/\*.*?\*/', '', css, flags=re.S)
    css = re.sub(r'\s+', ' ', css)
    css = re.sub(r'\s*([{};>])\s*', r'\1', css)
    css = re.sub(r';}', '}', css)
    return css.strip()


def c_array(name, data):
    lines = []
    for i in range(0, len(data), 24):
        lines.append('  ' + ','.join('0x%02x' % b for b in data[i:i + 24]) + ',')
    return 'const uint8_t %s[] PROGMEM = {\n%s\n};\n' % (name, '\n'.join(lines))


def main():
    # the PHP bundler wraps the JS the same way: a second copy of the bundle
    # (online arriving after the built-in one) must not run again
    js = 'if (!window.TeHyBug) {\n' + bundle('js', '\n;\n') + '\n}\n'
    css = bundle('css', '\n')
    js_min = minify_js(js)
    css_min = minify_css(css)
    # a broken minification must fail the build, not the device
    subprocess.run(['node', '--check', '/dev/stdin'], input=js_min, capture_output=True, text=True, check=True)
    js_gz = gzip.compress(js_min.encode('utf-8'), 9, mtime=0)
    css_gz = gzip.compress(css_min.encode('utf-8'), 9, mtime=0)
    stamp = hashlib.sha1(js_min.encode('utf-8') + css_min.encode('utf-8')).hexdigest()[:8]

    header = ('#pragma once\n'
              '// Generated by tools/embed-ui.py from html/v2 - do not edit.\n'
              '// The web UI, minified and gzipped, for the /ui/ fallback routes.\n'
              '#include <pgmspace.h>\n'
              '#define UI_BUNDLE_STAMP "%s"\n'
              'const size_t UI_JS_GZ_LEN = %d;\n%s'
              'const size_t UI_CSS_GZ_LEN = %d;\n%s'
              % (stamp, len(js_gz), c_array('UI_JS_GZ', js_gz), len(css_gz), c_array('UI_CSS_GZ', css_gz)))
    # --no-header: only the .build/ui files (for the mock) while a firmware
    # build may be reading the header
    if '--no-header' not in sys.argv and not (os.path.exists(OUT_H) and open(OUT_H).read() == header):
        open(OUT_H, 'w').write(header)
    os.makedirs(OUT_DIR, exist_ok=True)
    open(os.path.join(OUT_DIR, 'app.js.gz'), 'wb').write(js_gz)
    open(os.path.join(OUT_DIR, 'app.css.gz'), 'wb').write(css_gz)
    print('embed-ui: js %d -> %d -> %d B gz, css %d -> %d -> %d B gz, stamp %s'
          % (len(js), len(js_min), len(js_gz), len(css), len(css_min), len(css_gz), stamp))


if __name__ == '__main__':
    main()
