#pragma once
// Config-mode web interface: HTTP API, websocket push and logging.
#include "globals.h"
#include "sensors.h"
#include <ESP8266WebServer.h>
#include <WebSocketsServer.h>
#include <ArduinoJson.h>
#include <FS.h>
#include "debug.h"
#include "common_functions.h"
#include "fw_version.h"
// generated by tools/embed-ui.py (build.sh / PlatformIO): the device page for
// every build, the web UI copy only where flash allows it
#include "web_device_page.h"
#if !defined(ARDUINO_ESP8266_GENERIC)
#include "web_ui_bundle.h"
#endif

// Track exactly as many slots as the library will ever hand out
// (WEBSOCKETS_SERVER_CLIENT_MAX, 5). It was 10, so half the String objects
// could never be used and every push scanned them anyway.
constexpr uint8_t MAX_WEBSOCKET_CLIENTS = WEBSOCKETS_SERVER_CLIENT_MAX;
String websocketConnection[MAX_WEBSOCKET_CLIENTS];

// The page served at / lives in html/v2/device.html: the "loading the
// interface" page with the device's address, which loads the web UI from
// tehybug.com and falls back to the copy built into the firmware. It is
// gzipped into web_device_page.h by tools/embed-ui.py at build time and
// streamed from flash (it used to be copied into a heap String per load).

/* Device info / sensor JSON */

String getInfo() {
  DynamicJsonDocument root(1280);
  root["gumboardVersion"] = version;
  // exact build (YYMMDDHHMM): tells two builds of the same version apart
  root["fwBuild"] = buildTimestamp;
  // which board this binary targets ("universal" / "generic" / "display"), so
  // the web UI can show board-specific pages only where they apply
  root["board"] = BOARD_NAME;
  root["sketchSize"] = ESP.getSketchSize();
  root["freeSketchSpace"] = ESP.getFreeSketchSpace();
  root["wifiRSSI"] = String(WiFi.RSSI());
  root["wifiQuality"] = GetRSSIasQuality(WiFi.RSSI());
  root["wifiSSID"] = WiFi.SSID();
  root["ipAddress"] = WiFi.localIP().toString();
  root["freeHeap"] = ESP.getFreeHeap();
  root["chipID"] = ESP.getChipId();
  root["cpuFreqMHz"] = ESP.getCpuFreqMHz();
  root["sleepModeActive"] = tehybug.sleepEnabled();
  root["deepSleepMax"] = (int)(ESP.deepSleepMax() / 1000000);
  root["key"] = tehybug.device.key;
  root["uptimeS"] = millis() / 1000;
  root["apSsid"] = wifiSsid; // the device's own access point, for the portal instructions
  root["mdnsName"] = hostLabel(tehybug.device.deviceName); // <mdnsName>.local
#if !defined(ARDUINO_ESP8266_GENERIC)
  // which copy of the web UI is built in (the /ui/ fallback)
  root["uiBuild"] = UI_BUNDLE_STAMP;
#endif
  // What the start-up I2C scan found, so the UI can say which sensors and
  // modules are attached instead of leaving that to be inferred from which
  // readings happen to arrive.
  JsonObject detected = root.createNestedObject("detected");
  detected["bmx"] = tehybug.sensor.bmx;
  detected["bme680"] = tehybug.sensor.bme680;
  detected["aht20"] = tehybug.sensor.aht20;
  detected["am2320"] = tehybug.sensor.am2320;
  detected["max44009"] = tehybug.sensor.max44009;
  detected["sgp30"] = tehybug.sensor.sgp30;
  detected["ds3231"] = tehybug.peripherals.ds3231;
  detected["eeprom"] = tehybug.peripherals.eeprom;
  String json;
  serializeJson(root, json);
  return json;
}

String getSensor() {
  read_sensors();
  String json;
  serializeJson(tehybug.sensorData, json);
  return json;
}

/* Websocket push */

// sends the message to every websocket client connected on one of the urls
void sendToWebsocketClients(const String &message, std::initializer_list<const char *> urls) {
  if (webSocket.connectedClients() == 0) {
    return;
  }
  for (uint8_t i = 0; i < MAX_WEBSOCKET_CLIENTS; i++) {
    for (const char *url : urls) {
      if (websocketConnection[i] == url) {
        webSocket.sendTXT(i, message.c_str());
        break;
      }
    }
  }
}

void sendDeviceInfo() {
  // "/settings" included because the Cloud and Home Assistant settings pages
  // connect under that websocket url (see connectionStart in gumboard.js) and
  // display the device key. Without it those pages never received the info
  // message and their key field stayed on "Loading...".
  // "/firmware" included so the Downloads page can name the build this
  // device actually runs, rather than leaving the choice to guesswork.
  sendToWebsocketClients(
      getInfo(),
      {"/main", "/firststart", "/api/info", "/settings", "/firmware"});
}

void sendSensorData() {
  // "/datalog" and "/display_settings" included so their template fields can
  // offer "fill from my sensors" - those pages need to know which readings
  // this device produces.
  sendToWebsocketClients(getSensor(),
                         {"/main", "/settings", "/datalog", "/display_settings"});
}

void sendConfig() {
  sendToWebsocketClients(tehybug.conf.getConfig(),
                         {"/settings", "/setsensor", "/scenarios", "/setsystem",
                          "/datalog", "/display_settings"});
}

// Sends a log line to the dashboard websocket.
//
// Takes its arguments by reference (it used to copy both Strings on every
// call, and it is called on every MQTT publish and retry), and builds the JSON
// with ArduinoJson so a quote or backslash in a topic or payload can no longer
// produce malformed JSON on the wire. The payload is only built when a client
// is actually connected.
void Log(const String &function, const String &message) {
  D_println(function + ": " + message);
  if (webSocket.connectedClients() == 0) {
    return;
  }
  DynamicJsonDocument doc(512);
  const JsonObject log = doc.createNestedObject("log");
  log["function"] = function;
  log["message"] = message;
  String out;
  serializeJson(doc, out);
  sendToWebsocketClients(out, {"/main"});
}

/* HTTP API */

// Serves something gzipped at build time (the device page, the built-in web
// UI - see tools/embed-ui.py) straight from flash in small chunks: no heap
// copy. Cached by the browser with the firmware build as its ETag, since
// the content only changes with the firmware.
// `longCache`: the UI assets have their own URLs that only this server has,
// so a day in the browser cache is fine. The page at / is NOT cacheable
// that way: the same address serves the WiFi chooser while the portal is
// open, and a cached configuration page hid it. It revalidates every time
// instead - still a 304 from here when nothing changed.
void sendEmbedded(PGM_P contentType, PGM_P data, size_t length, bool longCache = true) {
  const String etag = "\"" + buildTimestamp + "\"";
  if (server.hasHeader(F("If-None-Match")) && server.header(F("If-None-Match")) == etag) {
    server.send(304, "text/plain", "");
    return;
  }
  server.sendHeader(F("Content-Encoding"), F("gzip"));
  server.sendHeader(F("Cache-Control"), longCache ? F("max-age=86400") : F("no-cache"));
  server.sendHeader(F("ETag"), etag);
  server.send_P(200, contentType, data, length);
}
#if !defined(ARDUINO_ESP8266_GENERIC)
void handleUiJs() { sendEmbedded(PSTR("text/javascript"), (PGM_P)UI_JS_GZ, UI_JS_GZ_LEN); }
void handleUiCss() { sendEmbedded(PSTR("text/css"), (PGM_P)UI_CSS_GZ, UI_CSS_GZ_LEN); }
#endif

void handleGetMainPage() {
  server.sendHeader("Access-Control-Allow-Origin", "*");
  sendEmbedded(PSTR("text/html"), (PGM_P)DEVICE_PAGE_GZ, DEVICE_PAGE_GZ_LEN, false);
}

void handleNotFound() {
  if (server.method() == HTTP_OPTIONS) {
    server.sendHeader("Access-Control-Allow-Origin", "*");
    server.send(204);
    return;
  }
  server.sendHeader("Location", "/update", true);
  server.send(302, "text/plain", "");
}

void handleSetConfig() {
  DynamicJsonDocument json(CONFIG_DOC_SIZE);
  const auto error = deserializeJson(json, server.arg("plain"));
  server.sendHeader("Connection", "close");
  if (error) {
    server.send(406, "application/json", "{\"response\":\"Not Acceptable\"}");
    return;
  }
  Log(F("SetConfig"), "Incoming Json length: " + String(measureJson(json)));
  JsonObject object = json.as<JsonObject>();
  // Answer before restarting. setConfig() restarts the chip itself when the
  // save carries reboot:true, and that used to happen before this handler
  // ever sent its response - so the browser saw the connection drop on every
  // successful save and could not tell it from a failed one. Take the flag
  // out, apply the rest, confirm, then restart.
  const bool reboot = object["reboot"] | false;
  object.remove("reboot");
  if (!tehybug.conf.setConfig(object)) {
    // Applied in RAM but not written to flash (pool overflow, or the file
    // system refused - see saveConfig). Confirming would be a lie, and a
    // restart now would discard even the RAM copy.
    server.send(500, "application/json", "{\"response\":\"Not saved\"}");
    return;
  }
  server.send(200, "application/json",
              reboot ? "{\"response\":\"OK\",\"reboot\":true}"
                     : "{\"response\":\"OK\"}");
  if (reboot) {
    server.client().stop(); // the response is out and the socket closed cleanly
    tehybug.pixel.off();
    delay(200);
    ESP.restart();
  }
}

void handleGetConfig() {
  server.sendHeader("Connection", "close");
  server.send(200, "application/json", tehybug.conf.getConfig());
}

void handleGetInfo() {
  server.sendHeader("Connection", "close");
  server.send(200, "application/json", getInfo());
}

void handleGetSensor() {
  server.sendHeader("Connection", "close");
  server.send(200, "application/json", getSensor());
}

// The address to reach the device on once you are back on your own network.
// Served plain so the config-mode page can show it while you are still on the
// device's own AP, where there is no internet and nothing else loads.
void handleGetIp() {
  server.sendHeader("Connection", "close");
  const IPAddress ip = WiFi.localIP();
  // 0.0.0.0 means the device has not joined a network yet — printing that as an
  // address to browse to just sends people to a dead end.
  server.send(200, "text/html",
              ip == IPAddress(0, 0, 0, 0)
                  ? String(F("not on your network yet - set WiFi first"))
                  : ip.toString());
}

// GET /api/datalog            -> {"active":...,"time":"...","files":[...]}
// GET /api/datalog?file=10.txt -> file content as text
void handleGetDataLog() {
  server.sendHeader("Access-Control-Allow-Origin", "*");
  server.sendHeader("Connection", "close");

  if (!tehybug.dataLogAvailable() || !tehybug.eeprom.mounted()) {
    server.send(200, "application/json", "{\"active\":false}");
    return;
  }

  if (server.hasArg("file")) {
    server.send(200, "text/plain", tehybug.eeprom.read(server.arg("file").c_str()));
    return;
  }

  tehybug.time.update();
  const String json = "{\"active\":true,\"timeSet\":" +
                      String(tehybug.time.isTimeSet() ? "true" : "false") +
                      ",\"time\":\"" + tehybug.time.timestamp() +
                      // detected chip capacity and the resulting day-file size,
                      // so the Data Log page can show which EEPROM was found
                      // instead of the user having to read the serial log
                      "\",\"capacity\":" + String(tehybug.eeprom.capacityBytes()) +
                      ",\"slotBytes\":" + String(tehybug.eeprom.slotBytes()) +
                      ",\"files\":" + tehybug.eeprom.listFilesJson() + "}";
  server.send(200, "application/json", json);
}

// GET /api/time -> {"rtc":true,"timeSet":...,"time":"YYYY-MM-DD HH:MM"}
// The DS3231 clock on its own — /api/datalog also reports the time, but only
// with the EEPROM module attached; the display board has an RTC regardless.
void handleGetTime() {
  server.sendHeader("Access-Control-Allow-Origin", "*");
  server.sendHeader("Connection", "close");
  if (!tehybug.peripherals.ds3231) {
    server.send(200, "application/json", "{\"rtc\":false}");
    return;
  }
  tehybug.time.update();
  server.send(200, "application/json",
              "{\"rtc\":true,\"timeSet\":" +
                  String(tehybug.time.isTimeSet() ? "true" : "false") +
                  ",\"time\":\"" + tehybug.time.timestamp() + "\"}");
}

// GET /api/settime?y=2026&mo=6&d=10&wd=4&h=18&mi=45&s=30
// sets the DS3231 clock (usually from the browser's local time)
void handleSetTime() {
  server.sendHeader("Access-Control-Allow-Origin", "*");
  server.sendHeader("Connection", "close");

  if (!tehybug.peripherals.ds3231) {
    server.send(409, "application/json", "{\"response\":\"No RTC detected\"}");
    return;
  }
  if (!server.hasArg("y") || !server.hasArg("mo") || !server.hasArg("d") ||
      !server.hasArg("h") || !server.hasArg("mi")) {
    server.send(400, "application/json", "{\"response\":\"Missing parameter\"}");
    return;
  }

  tehybug.time.setTime(server.arg("y").toInt(), server.arg("mo").toInt(),
                       server.arg("d").toInt(), server.arg("wd").toInt(),
                       server.arg("h").toInt(), server.arg("mi").toInt(),
                       server.arg("s").toInt());
  server.send(200, "application/json",
              "{\"response\":\"OK\",\"time\":\"" + tehybug.time.timestamp() + "\"}");
}

// GET /api/testtls?url=https://host/...&fp=AB:CD:...
//   -> {"ok":true,"host":"..."} when the TLS handshake succeeds with that
//      fingerprint (or unverified when fp is empty), otherwise
//      {"ok":false,"host":"...","code":N,"error":"..."} with BearSSL's reason.
// Lets the setup page check a pin against the real server before it is saved
// - a wrong or renewed certificate is otherwise only found out in the field,
// where the failed sends are silent. A throw-away client, so the shared one
// keeps whatever it was configured with.
void handleTestTls() {
  server.sendHeader("Connection", "close");
  DynamicJsonDocument doc(384);
#if defined(ARDUINO_ESP8266_GENERIC)
  doc["ok"] = false;
  doc["error"] = "this build has no TLS client";
#else
  const String url = server.arg("url");
  const String fp = server.arg("fp");
  const String host = hostOfUrl(url);
  doc["host"] = host;
  if (!url.startsWith("https://") || host.length() == 0) {
    doc["ok"] = false;
    doc["error"] = "not an https:// address";
  } else {
    BearSSL::WiFiClientSecure client;
    client.setBufferSizes(512, 512);
    client.setTimeout(5000);
    bool ok = true;
    if (fp.length() == 0) {
      client.setInsecure();
    } else if (!client.setFingerprint(fp.c_str())) {
      ok = false;
      doc["error"] = "fingerprint is malformed";
    }
    if (ok) {
      ok = client.connect(host.c_str(), portOfUrl(url));
      if (!ok) {
        char reason[96] = {0};
        const int code = client.getLastSSLError(reason, sizeof(reason));
        doc["code"] = code;
        doc["error"] = code != 0 ? String(reason) : String("could not connect (DNS, network, or the port is closed)");
      }
      client.stop();
    }
    doc["ok"] = ok;
    doc["verified"] = fp.length() > 0;
  }
#endif
  String out;
  serializeJson(doc, out);
  server.send(200, "application/json", out);
}

void setPortalRequest(); // sleep_modes.h, earlier in the sketch

// POST /api/wifiportal -> restarts into the WiFi portal ("Change WiFi
// network" in the web UI), without touching the saved credentials.
void handleWifiPortal() {
  server.sendHeader("Connection", "close");
  setPortalRequest();
  server.send(200, "application/json", "{\"response\":\"OK\",\"reboot\":true}");
  server.client().stop();
  tehybug.pixel.off();
  delay(200);
  ESP.restart();
}

void handleFactoryReset() {
  tehybug.pixel.on(255, 0, 0);
  D_println("Factory reset!");
#if !defined(ARDUINO_ESP8266_GENERIC)
  // Wipe the logged data on the external EEPROM too. Factory reset is triggered
  // by a 20s MODE-button hold, and the button shares GPIO0 with the I2C SDA
  // line — so wait for it to be released (with a timeout) before driving I2C,
  // then detect and format the EEPROM (setupSensors() hasn't mounted it yet on
  // this path).
  pinMode(BUTTON_PIN, INPUT_PULLUP);
  const unsigned long releaseStart = millis();
  while (digitalRead(BUTTON_PIN) == LOW && (millis() - releaseStart) < 5000) {
    delay(10);
  }
  // i2cBusBegin probes both port orientations - a data-log module attached
  // the mirrored way round must not survive a factory reset with its log
  // intact. (It also scans twice, which sensors like the AM2320 need.)
  i2cBusBegin();
  i2cScanner::Scanner &scanner = i2cScanner::shared();
  if (scanner.addressExists(0x50)) {
    tehybug.peripherals.eeprom = true;
    tehybug.eeprom.format();
  }
#endif
  SPIFFS.format();
  wifiManager.resetSettings();
  yield();
  ESP.restart();
}

/* Websocket events */

void webSocketEvent(uint8_t num, WStype_t type, uint8_t *payload,
                    size_t length) {
  switch (type) {
    case WStype_DISCONNECTED: {
        Log("WebSocketEvent", "[" + String(num) + "] Disconnected!");
        websocketConnection[num] = "";
        break;
      }
    case WStype_CONNECTED: {
        websocketConnection[num] = String((char *)payload);
        const IPAddress ip = webSocket.remoteIP(num);
        Log("WebSocketEvent", "[" + String(num) + "] Connected from " +
            ip.toString() +
            " url: " + websocketConnection[num]);
        // send message to client
        sendDeviceInfo();
        sendSensorData();
        sendConfig();
        break;
      }
    case WStype_TEXT: {
        if (((char *)payload)[0] == '{') {
          // Sized like the configuration itself (it was 1 KB): a whole-page
          // save carries every input on that page, and the Display & Alarms
          // page alone posts ~25 keys. Only alive in config mode, where the
          // heap is at its freest.
          DynamicJsonDocument json(CONFIG_DOC_SIZE);
          const auto error = deserializeJson(json, payload);
          // The result used to be ignored, so a payload that did not fit was
          // applied in part and the rest of the user's edits vanished with no
          // sign that anything went wrong. Refuse the whole save instead.
          if (error) {
            Log(F("WebSocketEvent"),
                String(F("Ignored a config that could not be parsed: ")) +
                    error.c_str());
            break;
          }
          Log("WebSocketEvent",
              "Incoming Json length: " + String(measureJson(json)));
          if (websocketConnection[num] == "/setConfig") {
            // extract the data
            JsonObject object = json.as<JsonObject>();
            tehybug.conf.setConfig(object);
          }
        }
        break;
      }
    default:
      break;
  }
}

void setupWebServer() {
  httpUpdater.setup(&server);
  server.on(F("/api/info"), HTTP_GET, handleGetInfo);
  server.on(F("/api/config"), HTTP_POST, handleSetConfig);
  server.on(F("/api/config"), HTTP_GET, handleGetConfig);
  server.on(F("/api/sensor"), HTTP_GET, handleGetSensor);
  server.on(F("/api/datalog"), HTTP_GET, handleGetDataLog);
  server.on(F("/api/time"), HTTP_GET, handleGetTime);
  server.on(F("/api/settime"), HTTP_GET, handleSetTime);
  server.on(F("/api/getip"), HTTP_GET, handleGetIp);
  server.on(F("/api/testtls"), HTTP_GET, handleTestTls);
  server.on(F("/api/wifiportal"), HTTP_POST, handleWifiPortal);
  server.on(F("/"), HTTP_GET, handleGetMainPage);
#if !defined(ARDUINO_ESP8266_GENERIC)
  server.on(F("/ui/app.js"), HTTP_GET, handleUiJs);
  server.on(F("/ui/app.css"), HTTP_GET, handleUiCss);
  // the server only keeps request headers it was told to; the built-in UI's
  // revalidation needs this one
  const char *kept[] = {"If-None-Match"};
  server.collectHeaders(kept, 1);
#endif
  server.onNotFound(handleNotFound);
  server.begin();

  webSocket.begin();
  webSocket.onEvent(webSocketEvent);
  Log(F("Setup"), F("Webserver started"));
}
